# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
list_1 =[2,3,4,2,12,4]
list_1


[2, 3, 4, 2, 12, 4]

In [2]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array


array([ 2,  3,  4,  2, 12,  4])

In [3]:
type(my_numpy_array)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([ [1,23,3], [2,3,21]])
my_matrix

array([[ 1, 23,  3],
       [ 2,  3, 21]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
the_numpy_matrix= np.array([ [3,7,9,3], [4,3,2,2]])
the_numpy_matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(90)
x

array([0.61461353, 0.06320835, 0.64133066, 0.58578468, 0.64833898,
       0.1319934 , 0.4381904 , 0.37786099, 0.81608078, 0.3372981 ,
       0.88782603, 0.56881289, 0.21154292, 0.09980177, 0.72831993,
       0.92400122, 0.32209995, 0.11176747, 0.59496639, 0.99810042,
       0.50712365, 0.93194507, 0.6290388 , 0.18853795, 0.50857251,
       0.27198746, 0.86429057, 0.44104798, 0.05774326, 0.07633858,
       0.44441362, 0.21896525, 0.57746513, 0.84134733, 0.40307519,
       0.36590567, 0.66454302, 0.13538599, 0.41370935, 0.08135302,
       0.35478898, 0.94429247, 0.61244234, 0.16393388, 0.54254059,
       0.21418308, 0.68128749, 0.10379146, 0.99505567, 0.00358725,
       0.63361804, 0.28723909, 0.4803151 , 0.09060548, 0.0281453 ,
       0.71206564, 0.43736726, 0.51968071, 0.31881772, 0.34299517,
       0.209816  , 0.79796454, 0.92276401, 0.60454693, 0.38162897,
       0.46687764, 0.09576491, 0.72961948, 0.90029142, 0.84395929,
       0.32657189, 0.49731501, 0.80471409, 0.0770956 , 0.59103

In [7]:
# you can create a matrix of random number as well
x = np.random.rand(2,4)
x

array([[5.58867250e-01, 1.12217179e-01, 2.86975000e-01, 7.50147861e-01],
       [3.20908028e-01, 3.19930688e-01, 5.78729206e-04, 7.67504131e-02]])

In [8]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(30)
x

11

In [9]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(12, 23, 4)
x

array([21, 13, 16, 22])

In [10]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,23)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [11]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# Matrix of ones
x = np.ones(4)
x

array([1., 1., 1., 1.])

In [13]:
# Array of zeros
x = np.zeros(4)
x

array([0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [14]:
num = int(input("Enter a number:"))
x = np.random.randint(0,num, 5)
x

Enter a number:5


array([3, 3, 0, 1, 2])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [15]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,13)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
y = np.arange(8,20)
y

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [18]:
square = x ** 2
square

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [19]:
sqrt = np.sqrt(square)
sqrt

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [20]:
z = np.exp(y)
z

array([2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [21]:

X = [5, 7, 20]
Y = [9, 15, 4]

x = np.array(X)
y = np.array(Y)

In [22]:
sub = x - y
sub

array([-4, -8, 16])

In [23]:
sqr = sub ** 2
sqrt = np.sqrt(sqr)
sqrt

array([ 4.,  8., 16.])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [24]:
my_numpy_array = np.array([1,3,4,2,44,2,4,6,7,87])
my_numpy_array

array([ 1,  3,  4,  2, 44,  2,  4,  6,  7, 87])

In [25]:
# Access specific index from the numpy array
my_numpy_array[1]

3

In [26]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[1: 5]

array([ 3,  4,  2, 44])

In [27]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[1: 3] = 13
my_numpy_array

array([ 1, 13, 13,  2, 44,  2,  4,  6,  7, 87])

In [28]:
# Let's define a two dimensional numpy array
my_matrix = np.random.randint(1,34,(4,4))
my_matrix

array([[ 3,  9, 29, 12],
       [32, 11,  7,  5],
       [ 5, 31, 18, 20],
       [14, 29, 14, 13]])

In [29]:
# Get a row from a mtrix
my_matrix[1]

array([32, 11,  7,  5])

In [30]:
# Get one element
my_matrix[1][1]

11

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [31]:
X = np.array([[2 ,30, 20 ,-2 ,-4],
    [3, 4 , 40 ,-3 ,-2],
    [-3 ,4, -6, 90, 10],
    [25, 45 ,34 ,22 ,12],
    [13 ,24, 22, 32, 37]])
X[4][0:5] =0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [32]:
m = np.random.randint(1,34,(3,4))
m

array([[12, 25, 21,  5],
       [29, 25, 25, 17],
       [ 2, 30, 24,  6]])

In [33]:
mn = m[m>28]
mn

array([29, 30])

In [34]:
# Obtain odd elements only
mn = m [m % 2 == 1]
mn

array([25, 21,  5, 29, 25, 25, 17])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [35]:
X = np.array([[2, 30 ,20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25 ,45 ,34 ,22 ,12],
    [13 ,24, 22, 32, 37]])
X[ X < 0 ] = 0
X [ X % 2 == 1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [36]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [37]:
import pandas as pd

In [38]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df = pd.DataFrame({ 'Bank Client ID': [12,34,22],
                                'Bank Client Name': ['Jimin', 'Jungkook', 'Rm'],
                              'Net Worth [$]': [3500,88, 44] })
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]
0              12            Jimin           3500
1              34         Jungkook             88
2              22               Rm             44

In [39]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [40]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth [$]
0              12            Jimin           3500
1              34         Jungkook             88

In [41]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth [$]
1              34         Jungkook             88
2              22               Rm             44

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [42]:
portfolio_df = pd.DataFrame({'number of shares': [21,4,5],
                            'stock ticker symbols': ['aaaple','google','amazon'],
                            'price per share': [23,33,22]})
portfolio_df

number of shares stock ticker symbols  price per share
0                21               aaaple               23
1                 4               google               33
2                 5               amazon               22

In [43]:
stocks_dollar_value = portfolio_df['number of shares']* portfolio_df['price per share']
stocks_dollar_value

0    483
1    132
2    110
dtype: int64

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [44]:
!pip install lxml

In [45]:
!python -m pip install --upgrade pip

In [47]:
# Pandas is used to read a csv file and store data in a DataFrame
house_price_df= pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
house_price_df

[                                        Year of birth  \
 0                                      1937 and prior   
 1                                                1938   
 2                                                1939   
 3                                                1940   
 4                                                1941   
 5                                                1942   
 6                                             1943-54   
 7                                                1955   
 8                                                1956   
 9                                                1957   
 10                                               1958   
 11                                               1959   
 12                                     1960 and later   
 13  Notes: 1. Persons born on January 1 of any yea...   
 
                                                   Age  
 0                                                  65  
 1            

In [ ]:
stocks_dollar_value

In [ ]:
# Read tabular data using read_html


MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
https://www.ssa.gov/oact/progdata/nra.html

# TASK #8: PANDAS OPERATIONS

In [49]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [51]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df [ bank_client_df['Years with bank']>= 5]
df_loyal

Bank client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [53]:
# Delete a column from a DataFrame
del bank_client_df['Bank client ID']
bank_client_df

Bank Client Name  Net worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [57]:
high_nw = bank_client_df[bank_client_df['Net worth [$]']>= 5000]
high_nw['Net worth [$]'].sum()

39000

# TASK #9: PANDAS WITH FUNCTIONS

In [3]:
# Let's define a dataframe as follows:
import pandas as pd
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [4]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance *1.2

In [5]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [6]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [7]:
def triple_stock(price):
    return (price *3 )+200

In [8]:
stocks_df = pd.DataFrame({'price': [12,34,221]})
reult = stocks_df['price'].apply(triple_stock)
result.sum()

0    236
1    302
2    863
Name: price, dtype: int64

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [9]:
# Let's define a dataframe as follows:
import pandas as pd
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [10]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [11]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [12]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by = 'Years with bank', inplace = True)

In [13]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [14]:
df1 = pd.DataFrame({ 'A' : ['A0', 'A1', 'A2', 'A3'],
                     'B' : ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3']
                   }, index = [0,1,2,3])
df1

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [18]:
df2 = pd.DataFrame({ 'A' : ['A4', 'A5', 'A6', 'A7'],
                     'B' : ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7']
                   }, index = [4,5,6,7])
df2

A   B   C
4  A4  B4  C4
5  A5  B5  C5
6  A6  B6  C6
7  A7  B7  C7

In [17]:
df3 = pd.DataFrame({ 'A' : ['A8', 'A9', 'A10', 'A11'],
                     'B' : ['B8', 'B9', 'B10', 'B11'],
                      'C': ['C8', 'C9', 'C10', 'C11']
                   }, index = [8,9,10,11])
df3

A    B    C
8    A8   B8   C8
9    A9   B9   C9
10  A10  B10  C10
11  A11  B11  C11

In [19]:
pd.concat([df1, df2, df3])

A    B    C
0    A0   B0   C0
1    A1   B1   C1
2    A2   B2   C2
3    A3   B3   C3
4    A4   B4   C4
5    A5   B5   C5
6    A6   B6   C6
7    A7   B7   C7
8    A8   B8   C8
9    A9   B9   C9
10  A10  B10  C10
11  A11  B11  C11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [32]:
import pandas as pd
bank_df1 = pd.DataFrame({'first name' : ['Park', 'Kim', 'Min'],
                         'last name' : ['Jimin', 'Namjoon', 'Yoongi'], 'Bank Id' :[1,2,3]}
                        )
bank_df1

first name last name  Bank Id
0       Park     Jimin        1
1        Kim   Namjoon        2
2        Min    Yoongi        3

In [33]:
bank_df2 = pd.DataFrame({'first name' : ['Jung', 'Kim', 'Jeon','Kim'],
                         'last name' : ['Hoseok', 'Taehyung', 'Jungkook', 'SeokJin'],
                        'Bank Id' :[4,5,6,7]}
                        )
bank_df2

first name last name  Bank Id
0       Jung    Hoseok        4
1        Kim  Taehyung        5
2       Jeon  Jungkook        6
3        Kim   SeokJin        7

In [43]:
bank_df_all = pd.concat([bank_df1, bank_df2])

In [44]:


bank_df_salary = pd.DataFrame({'salary' : [1223,33434,3323,1221,44446,878,7656],
                       'Bank Id': [1,2,3,4,5,6,7]})


In [46]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary , on = 'Bank Id')
bank_df_all

first name last name  Bank Id  salary
0       Park     Jimin        1    1223
1        Kim   Namjoon        2   33434
2        Min    Yoongi        3    3323
3       Jung    Hoseok        4    1221
4        Kim  Taehyung        5   44446
5       Jeon  Jungkook        6     878
6        Kim   SeokJin        7    7656

In [58]:
new_client = { 'first name': ['BTS'],
             'last name': ['Army'],
              'Bank Id': [8],
             'salary ':[777777]
             }
new_client_df = pd.DataFrame(new_client , columns = [ 'first name', 'last name' , 'Bank Id', 'salary '])




In [59]:

new_client_df

first name last name  Bank Id  salary 
0        BTS      Army        8   777777

In [60]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

first name last name  Bank Id   salary   salary 
0       Park     Jimin        1   1223.0       NaN
1        Kim   Namjoon        2  33434.0       NaN
2        Min    Yoongi        3   3323.0       NaN
3       Jung    Hoseok        4   1221.0       NaN
4        Kim  Taehyung        5  44446.0       NaN
5       Jeon  Jungkook        6    878.0       NaN
6        Kim   SeokJin        7   7656.0       NaN
0        BTS      Army        8      NaN  777777.0

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [48]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

[                                        Year of birth  \
 0                                      1937 and prior   
 1                                                1938   
 2                                                1939   
 3                                                1940   
 4                                                1941   
 5                                                1942   
 6                                             1943-54   
 7                                                1955   
 8                                                1956   
 9                                                1957   
 10                                               1958   
 11                                               1959   
 12                                     1960 and later   
 13  Notes: 1. Persons born on January 1 of any yea...   
 
                                                   Age  
 0                                                  65  
 1            

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200 

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df